story_dir: &story_dir generated_stories/example

story_writer:
    tool: qa_outline_story_writer
    cfg:
        max_conv_turns: 3
        num_scene: 8
        temperature: 0.5
    params:
        # story_topic: "Time Management: A child learning how to manage their time effectively."
        # main_role: "(no main role specified)"
        # scene: "(no scene specified)"
        text: "옛날 옛적에 말이다, 산 너머 산 밑에 조그만 마을에 흥부 놀부 형제가 살았어. 두 형제가 한 부모 밑에서 자랐는데, 어릴 적엔 둘 다 뭐 착하고 말 잘 듣고 그랬지. 근데 크고 나니까 아이고야, 어째 그렇게 달라질 수가 있노. 형 놀부는 말야, 욕심 많고 성질도 까칠하고, 머리 굴리는 데는 빠른데 마음은 좀 좁았고. 근데 동생 흥부는 거 참, 가난은 해도 마음이 곱고 사람 좋은 그런 사람이었어.

      부모님 돌아가시고 나서 형 놀부가 집이랑 땅 다 차지해버렸어. 동생한테는 콩 한 쪽도 안 나눠주고 말이야. “너는 너 살 길 찾아봐라” 하면서 내쫓아버렸지 뭐야. 흥부는 그 와중에도 “그래도 형인데…” 하면서 불평 한 마디 안 하고 처자식이랑 나와서 초가집 한 칸 지어 살았지.

      살림이 말이 아니었어. 먹을 거도 없고, 애들은 줄줄이 많고, 밥은커녕 죽도 못 끓일 날이 많았거든. 그래도 흥부는 매일 산에 나무 하러 가고, 아낙은 들일 도우러 가고… 힘들어도 남 원망은 안 했지.

      그런 어느 날이었어. 흥부가 마루에서 장작을 패고 있는데, 제비 한 마리가 날아와서 처마 밑에 꽁지를 탁 부러뜨려서 떨어진 거야. 아이고 이놈아, 하면서 보니까 다리뼈가 부러졌더라고. 흥부는 그걸 그냥 지나치질 못하지. 솜이불 조금 찢어서 정성껏 싸매주고, 밥풀 조금 얻어다가 먹이고… 날마다 지극정성으로 보살폈단 말이지.

      그러고 며칠 지나고 한참 봄이 다 되니까, 제비가 다리가 싹 낫고는 날아서 갔지. 그냥 간 게 아니고, 며칠 뒤에 입에 뭔가를 물고 다시 왔어. 집 앞 마당에 ‘요거 가져가라’ 하고 툭 떨어뜨리고는 휙 날아가더란 말이지. 그게 뭔가 하고 보니까, 호박씨 한 줌이더라고.

      흥부는 “이놈이 나한테 은혜 갚으러 왔나?” 하면서 그 호박씨를 뜰 앞에 심었지. 그런데 웬일이냐, 이 호박이 그냥 호박이 아닌 거야. 하루가 다르게 자라서 담장을 넘고, 지붕을 덮고, 줄기는 장독대를 감더니 커다란 호박이 세 개가 주렁주렁 열린 거야.

      “이제 우리 애들 호박죽이라도 끓여주자” 하면서 그 호박을 따다가 톱으로 켰는데… 아이고 이게 뭐시다냐, 첫 번째 호박에서 쌀이 와르르, 두 번째 호박에서는 금덩이가 우르르, 세 번째는 온갖 비단이 질질 나오는 거라! 아이고야, 거지살이 하던 흥부네가 하루아침에 부자가 되어버린 거지 뭐야.

      그 소문이 어디 가겠노, 금방 놀부 귀에 들어갔지. “흥부 저놈이 뭘 해서 부자가 됐다고? 제비?” 이러면서 놀부는 바로 제비를 찾아다니다가 억지로 한 마리 잡아다가 일부러 다리를 뚝 부러뜨린 거야. 그리고는 “야, 나도 은혜 갚아라!” 하면서 싸매주고는 기다렸지.

      제비도 얼결에 나았다 싶더니, 얼마 안 있어 놀부 집에도 씨 한 줌 떨어뜨리고 갔지 뭐야. 놀부는 “드디어 왔다!” 하면서 좋아 죽고, 씨를 심었는데… 이것도 호박이 주렁주렁 열렸거든? 그런데 이게 또 어찌나 빠르게 자라던지.

      그래서 냅다 호박을 톱으로 팍팍 켰더니… 첫 번째 호박에선 뱀이 퉁! 하고 튀어나와 물고, 두 번째는 도깨비들이 우르르르르르르! 막 뛰어나와 집안을 뒤집어놓고, 세 번째는 뭐냐, 똥물이 확 튀어서 집이 엉망진창이 돼버렸지. 놀부는 그만 깜짝 놀라서 뒤로 자빠져 코피 터지고, 집은 망가지고, 살림도 박살나고.

      그렇게 욕심 부리다가 망한 놀부는 결국 흥부네 찾아와서 무릎 꿇고 “내가 잘못했네. 미안하다, 동생아…” 하면서 사죄했지. 흥부는 또 그걸 안 받아줄 사람이 아니지. “형, 그래도 우리 형제인데…” 하면서 다시 형 손 잡고 같이 살아가게 됐다더라.

      그리하여 두 형제는 다시 한집에 살면서, 놀부도 좀 착해지고, 흥부네는 여전히 사람 좋고, 제비는 또 해마다 찾아오고… 그렇게 마을엔 다시 웃음꽃이 피었다지 뭐냐."
# sound_generation:
#     tool: audioldm2_t2a
#     cfg:
#         num_turns: 3
#         device: cuda
#         sample_rate: &sample_rate 16000
#     params:
#         guidance_scale: 3.5
#         seed: 0
#         ddim_steps: 200
#         n_candidate_per_text: 3


speech_generation:
    tool: cosyvoice_tts
    cfg:
        sample_rate: &sample_rate 16000
    params:
        voice: en-US-JennyNeural


image_generation:
    tool: story_diffusion_t2i
    cfg:
        num_turns: 3
        model_name: stabilityai/stable-diffusion-xl-base-1.0
        id_length: 2
        height: &image_height 576
        width: &image_width 320
    params:
        seed: 112536
        guidance_scale: 10.0
        style_name: "Storybook" # ['(No style)', 'Japanese Anime', 'Digital/Oil Painting', 'Pixar/Disney Character', 
                                #  'Photographic', 'Comic book', 'Line art', 'Black and White Film Noir', 'Isometric Rooms']

music_generation:
    tool: musicgen_t2m
    cfg:
        llm_type: qwen
        num_turns: 3
        device: cuda
    params:
        duration: 30.0

video_compose:
    tool: slideshow_video_compose
    cfg:
        {}
    params:
        height: *image_height
        width: *image_width
        story_dir: *story_dir
        fps: 8
        audio_sample_rate: *sample_rate
        audio_codec: mp3
        caption:
            font: resources/font/msyh.ttf
            # bg_color: LightGrey
            fontsize: 32
            color: white
            # stroke_color: white
            # stroke_width: 0.5
            max_length: 50
        slideshow_effect:
            bg_speech_ratio: 0.6
            sound_volume: 0.6
            music_volume: 0.5
            fade_duration: 0.8
            slide_duration: 0.4
            zoom_speed: 0.5
            move_ratio: 0.9
    